package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"
	"fmt"
	"project-abyssoftime-cms-v2/api/graphql/generated"
	"project-abyssoftime-cms-v2/api/graphql/model"
)

// SaveDocument is the resolver for the saveDocument field.
func (r *mutationResolver) SaveDocument(ctx context.Context, entryID string, locale *string, data map[string]any) (*model.Document, error) {
	panic(fmt.Errorf("not implemented: SaveDocument - saveDocument"))
}

// PublishDocument is the resolver for the publishDocument field.
func (r *mutationResolver) PublishDocument(ctx context.Context, entryID string, locale *string) (*model.Document, error) {
	panic(fmt.Errorf("not implemented: PublishDocument - publishDocument"))
}

// UnpublishDocument is the resolver for the unpublishDocument field.
func (r *mutationResolver) UnpublishDocument(ctx context.Context, entryID string, locale *string) (*model.Document, error) {
	panic(fmt.Errorf("not implemented: UnpublishDocument - unpublishDocument"))
}

// DeleteDocument is the resolver for the deleteDocument field.
func (r *mutationResolver) DeleteDocument(ctx context.Context, entryID string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteDocument - deleteDocument"))
}

// PublishedDocument is the resolver for the publishedDocument field.
func (r *queryResolver) PublishedDocument(ctx context.Context, entryID string, locale *string) (*model.Document, error) {
	panic(fmt.Errorf("not implemented: PublishedDocument - publishedDocument"))
}

// ContentTypes is the resolver for the contentTypes field.
func (r *queryResolver) ContentTypes(ctx context.Context) ([]*model.ContentType, error) {
	panic(fmt.Errorf("not implemented: ContentTypes - contentTypes"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
