package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"
	"project-abyssoftime-cms-v2/api/graphql/generated"
	"project-abyssoftime-cms-v2/api/graphql/model"
	"project-abyssoftime-cms-v2/api/internal/delivery/http/middleware"
	"project-abyssoftime-cms-v2/api/internal/domain/entity"
	pkgerrors "project-abyssoftime-cms-v2/api/pkg/errors"
)

// SaveDocument is the resolver for the saveDocument field.
func (r *mutationResolver) SaveDocument(ctx context.Context, contentTypeSlug string, documentID string, locale *string, data map[string]any) (*model.Document, error) {
	loc := ""
	if locale != nil {
		loc = *locale
	}
	doc := &entity.Document{DocumentID: documentID, Data: data, Locale: loc}
	saved, err := r.DocumentUC.Save(ctx, contentTypeSlug, doc, middleware.UserID(ctx))
	if err != nil {
		return nil, err
	}
	return toModelDocument(saved), nil
}

// PublishDocument is the resolver for the publishDocument field.
func (r *mutationResolver) PublishDocument(ctx context.Context, contentTypeSlug string, documentID string, locale *string) (*model.Document, error) {
	loc := ""
	if locale != nil {
		loc = *locale
	}
	if err := r.DocumentUC.Publish(ctx, contentTypeSlug, documentID, loc, middleware.UserID(ctx)); err != nil {
		return nil, err
	}
	doc, err := r.DocumentUC.GetPublished(ctx, contentTypeSlug, documentID, loc)
	if err != nil {
		return nil, err
	}
	return toModelDocument(doc), nil
}

// UnpublishDocument is the resolver for the unpublishDocument field.
func (r *mutationResolver) UnpublishDocument(ctx context.Context, contentTypeSlug string, documentID string, locale *string) (*model.Document, error) {
	loc := ""
	if locale != nil {
		loc = *locale
	}
	if err := r.DocumentUC.Unpublish(ctx, contentTypeSlug, documentID, loc); err != nil {
		return nil, err
	}
	draft, _, err := r.DocumentUC.GetForEdit(ctx, contentTypeSlug, documentID, loc)
	if err != nil {
		return nil, err
	}
	return toModelDocument(draft), nil
}

// DeleteDocument is the resolver for the deleteDocument field.
func (r *mutationResolver) DeleteDocument(ctx context.Context, contentTypeSlug string, documentID string) (bool, error) {
	if err := r.DocumentUC.Delete(ctx, contentTypeSlug, documentID); err != nil {
		return false, err
	}
	return true, nil
}

// PublishedDocument is the resolver for the publishedDocument field.
func (r *queryResolver) PublishedDocument(ctx context.Context, contentTypeSlug string, documentID string, locale *string) (*model.Document, error) {
	loc := ""
	if locale != nil {
		loc = *locale
	}
	doc, err := r.DocumentUC.GetPublished(ctx, contentTypeSlug, documentID, loc)
	if err != nil {
		if pkgerrors.Is(err, pkgerrors.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return toModelDocument(doc), nil
}

// ContentTypes is the resolver for the contentTypes field.
func (r *queryResolver) ContentTypes(ctx context.Context) ([]*model.ContentType, error) {
	cts, err := r.ContentTypeUC.FindAll(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.ContentType, len(cts))
	for i, ct := range cts {
		result[i] = &model.ContentType{
			ID:        ct.ID,
			Name:      ct.Name,
			Slug:      ct.Slug,
			Kind:      string(ct.Kind),
			CreatedAt: ct.CreatedAt,
			UpdatedAt: ct.UpdatedAt,
		}
	}
	return result, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
