// Code generator: reads content-types/*.json → produces .graphql schema files,
// resolver implementations, and gqlgen.yml model mappings.
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"

	"project-abyssoftime-cms-v2/api/internal/domain/entity"
	contenttype "project-abyssoftime-cms-v2/api/internal/usecase/content_type"
)

func main() {
	phase := flag.String("phase", "all", "schema | resolvers | all")
	flag.Parse()

	rootDir, err := findRootDir()
	if err != nil {
		log.Fatalf("find root dir: %v", err)
	}

	contentTypesDir := filepath.Join(rootDir, "content-types")
	graphqlDir := filepath.Join(rootDir, "graphql")

	defs, err := contenttype.LoadDefinitions(contentTypesDir)
	if err != nil {
		log.Fatalf("load content-type definitions: %v", err)
	}

	switch *phase {
	case "schema":
		if err := generateSchema(graphqlDir, defs); err != nil {
			log.Fatalf("generate schema: %v", err)
		}
		if err := injectModels(graphqlDir, defs); err != nil {
			log.Fatalf("inject models: %v", err)
		}
	case "resolvers":
		if err := generateResolvers(graphqlDir, defs); err != nil {
			log.Fatalf("generate resolvers: %v", err)
		}
	case "all":
		if err := generateSchema(graphqlDir, defs); err != nil {
			log.Fatalf("generate schema: %v", err)
		}
		if err := injectModels(graphqlDir, defs); err != nil {
			log.Fatalf("inject models: %v", err)
		}
		if err := generateResolvers(graphqlDir, defs); err != nil {
			log.Fatalf("generate resolvers: %v", err)
		}
	default:
		log.Fatalf("unknown phase: %s (expected schema, resolvers, or all)", *phase)
	}

	log.Printf("gqlcodegen: phase=%s completed for %d content types", *phase, len(defs))
}

func findRootDir() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found")
		}
		dir = parent
	}
}

// ── Schema Generation ──

func generateSchema(graphqlDir string, defs []contenttype.ContentTypeDefinition) error {
	schemaDir := filepath.Join(graphqlDir, "schema")
	if err := os.MkdirAll(schemaDir, 0o755); err != nil {
		return err
	}

	if err := os.WriteFile(filepath.Join(schemaDir, "base.graphql"), []byte(buildBaseSchema()), 0o644); err != nil {
		return fmt.Errorf("write base.graphql: %w", err)
	}

	for _, def := range defs {
		sdl := buildContentTypeSDL(def)
		filename := def.Slug + ".graphql"
		if err := os.WriteFile(filepath.Join(schemaDir, filename), []byte(sdl), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", filename, err)
		}
	}

	return nil
}

func buildBaseSchema() string {
	return `# Code generated by gqlcodegen. DO NOT EDIT.

directive @auth on FIELD_DEFINITION

scalar JSON
scalar Time

enum SortOrder {
  ASC
  DESC
}

input IDFilter {
  eq: ID
  ne: ID
  in: [ID!]
  notIn: [ID!]
}

input StringFilter {
  eq: String
  ne: String
  in: [String!]
  notIn: [String!]
}

input NumberFilter {
  eq: Float
  ne: Float
  in: [Float!]
  notIn: [Float!]
}

input BooleanFilter {
  eq: Boolean
  ne: Boolean
}

input TimeFilter {
  eq: Time
  ne: Time
}

type MediaAsset {
  documentId: ID!
  url: String!
  thumbnailUrl: String
  fileName: String
  width: Int
  height: Int
}

type ContentType {
  id: ID!
  name: String!
  slug: String!
  kind: String!
  createdAt: Time!
  updatedAt: Time!
}

type Query {
  contentTypes: [ContentType!]!
}

type Mutation {
  _empty: Boolean
}
`
}

func buildContentTypeSDL(def contenttype.ContentTypeDefinition) string {
	typeName := slugToPascalCase(def.Slug)
	camel := slugToCamelCase(def.Slug)

	var builder strings.Builder
	builder.WriteString("# Code generated by gqlcodegen. DO NOT EDIT.\n\n")

	for _, field := range def.Fields {
		if field.Type == "component" {
			writeComponentType(&builder, typeName, field)
		}
	}

	fmt.Fprintf(&builder, "type %s {\n", typeName)
	builder.WriteString("  documentId: ID!\n")
	for _, field := range def.Fields {
		if field.Type == "component" {
			compType := typeName + slugToPascalCase(field.Name)
			if field.Repeatable {
				fmt.Fprintf(&builder, "  %s: [%s!]\n", field.Name, compType)
			} else {
				fmt.Fprintf(&builder, "  %s: %s\n", field.Name, compType)
			}
			continue
		}
		fmt.Fprintf(&builder, "  %s: %s\n", field.Name, fieldTypeToGraphQL(field.Type))
	}
	builder.WriteString("  locale: String!\n")
	builder.WriteString("  createdAt: Time!\n")
	builder.WriteString("  updatedAt: Time!\n")
	builder.WriteString("  publishedAt: Time\n")
	builder.WriteString("}\n\n")

	fmt.Fprintf(&builder, "input %sInput {\n", typeName)
	for _, field := range def.Fields {
		if field.Type == "component" {
			continue
		}
		fmt.Fprintf(&builder, "  %s: %s\n", field.Name, fieldTypeToInputGraphQL(field.Type))
	}
	builder.WriteString("}\n\n")

	if def.Kind == "collection" {
		writeFilterType(&builder, typeName, def.Fields)
		writeOrderByType(&builder, typeName, def.Fields)
	}

	if def.Kind == "collection" {
		builder.WriteString("extend type Query {\n")
		fmt.Fprintf(&builder, "  %s(documentId: ID!, locale: String, status: String): %s\n", camel, typeName)
		fmt.Fprintf(&builder, "  %s(filters: [%sFilter!], orderBy: %sOrderBy, start: Int, size: Int, locale: String, status: String): [%s!]!\n", pluralize(camel), typeName, typeName, typeName)
		builder.WriteString("}\n\n")

		builder.WriteString("extend type Mutation {\n")
		fmt.Fprintf(&builder, "  create%s(data: %sInput!): %s! @auth\n", typeName, typeName, typeName)
		fmt.Fprintf(&builder, "  update%s(documentId: ID!, data: %sInput!): %s! @auth\n", typeName, typeName, typeName)
		fmt.Fprintf(&builder, "  delete%s(documentId: ID!): Boolean! @auth\n", typeName)
		fmt.Fprintf(&builder, "  publish%s(documentId: ID!, locale: String): %s! @auth\n", typeName, typeName)
		fmt.Fprintf(&builder, "  unpublish%s(documentId: ID!, locale: String): %s! @auth\n", typeName, typeName)
		builder.WriteString("}\n")
	} else {
		builder.WriteString("extend type Query {\n")
		fmt.Fprintf(&builder, "  %s(locale: String, status: String): %s\n", camel, typeName)
		builder.WriteString("}\n\n")

		builder.WriteString("extend type Mutation {\n")
		fmt.Fprintf(&builder, "  save%s(data: %sInput!, locale: String): %s! @auth\n", typeName, typeName, typeName)
		fmt.Fprintf(&builder, "  publish%s(locale: String): %s! @auth\n", typeName, typeName)
		fmt.Fprintf(&builder, "  unpublish%s(locale: String): %s! @auth\n", typeName, typeName)
		builder.WriteString("}\n")
	}

	return builder.String()
}

func writeComponentType(builder *strings.Builder, parentType string, field entity.FieldDefinition) {
	compType := parentType + slugToPascalCase(field.Name)

	for _, sub := range field.Fields {
		if sub.Type == "component" {
			writeComponentType(builder, compType, sub)
		}
	}

	fmt.Fprintf(builder, "type %s {\n", compType)
	for _, sub := range field.Fields {
		if sub.Type == "component" {
			nestedType := compType + slugToPascalCase(sub.Name)
			if sub.Repeatable {
				fmt.Fprintf(builder, "  %s: [%s!]\n", sub.Name, nestedType)
			} else {
				fmt.Fprintf(builder, "  %s: %s\n", sub.Name, nestedType)
			}
			continue
		}
		fmt.Fprintf(builder, "  %s: %s\n", sub.Name, fieldTypeToGraphQL(sub.Type))
	}
	builder.WriteString("}\n\n")
}

func writeFilterType(builder *strings.Builder, typeName string, fields []entity.FieldDefinition) {
	fmt.Fprintf(builder, "input %sFilter {\n", typeName)
	builder.WriteString("  documentId: IDFilter\n")
	builder.WriteString("  createdAt: TimeFilter\n")
	builder.WriteString("  updatedAt: TimeFilter\n")
	builder.WriteString("  publishedAt: TimeFilter\n")
	for _, field := range fields {
		switch field.Type {
		case "text", "richtext":
			fmt.Fprintf(builder, "  %s: StringFilter\n", field.Name)
		case "number":
			fmt.Fprintf(builder, "  %s: NumberFilter\n", field.Name)
		case "boolean":
			fmt.Fprintf(builder, "  %s: BooleanFilter\n", field.Name)
		}
	}
	fmt.Fprintf(builder, "  and: [%sFilter!]\n", typeName)
	fmt.Fprintf(builder, "  or: [%sFilter!]\n", typeName)
	fmt.Fprintf(builder, "  not: %sFilter\n", typeName)
	builder.WriteString("}\n\n")
}

func writeOrderByType(builder *strings.Builder, typeName string, fields []entity.FieldDefinition) {
	fmt.Fprintf(builder, "input %sOrderBy {\n", typeName)
	for _, field := range fields {
		switch field.Type {
		case "text", "richtext", "number", "boolean":
			fmt.Fprintf(builder, "  %s: SortOrder\n", field.Name)
		}
	}
	builder.WriteString("  createdAt: SortOrder\n")
	builder.WriteString("  updatedAt: SortOrder\n")
	builder.WriteString("  publishedAt: SortOrder\n")
	builder.WriteString("}\n\n")
}

// ── Resolver Generation ──

func generateResolvers(graphqlDir string, defs []contenttype.ContentTypeDefinition) error {
	resolverDir := filepath.Join(graphqlDir, "resolver")
	if err := os.MkdirAll(resolverDir, 0o755); err != nil {
		return err
	}

	var builder strings.Builder
	builder.WriteString("// Code generated by gqlcodegen from content-types/*.json. DO NOT EDIT.\n")
	builder.WriteString("package resolver\n\n")
	builder.WriteString("import (\n")
	builder.WriteString("\t\"context\"\n")
	builder.WriteString("\t\"time\"\n\n")
	builder.WriteString("\t\"project-abyssoftime-cms-v2/api/graphql/generated\"\n")
	builder.WriteString("\t\"project-abyssoftime-cms-v2/api/graphql/model\"\n")
	builder.WriteString("\t\"project-abyssoftime-cms-v2/api/internal/domain/entity\"\n")
	builder.WriteString(")\n\n")
	builder.WriteString("// Ensure unused imports are used.\n")
	builder.WriteString("var _ time.Time\n")
	builder.WriteString("var _ context.Context\n\n")

	writeResolverTypes(&builder)

	for _, def := range defs {
		writeFieldDefinitions(&builder, def)
		builder.WriteString("\n")

		if def.Kind == "collection" {
			writeCollectionResolvers(&builder, def)
		} else {
			writeSingleResolvers(&builder, def)
		}
		builder.WriteString("\n")
	}

	writeResolverRootMethods(&builder, defs)
	writeMapFieldResolvers(&builder, defs)

	outPath := filepath.Join(resolverDir, "content_gen.go")
	return os.WriteFile(outPath, []byte(builder.String()), 0o644)
}

func writeResolverTypes(builder *strings.Builder) {
	builder.WriteString("// ── Resolver types + root methods ──\n\n")
	builder.WriteString("type queryResolver struct{ *Resolver }\n")
	builder.WriteString("type mutationResolver struct{ *Resolver }\n\n")
	builder.WriteString("func (resolver *Resolver) Query() generated.QueryResolver       { return &queryResolver{resolver} }\n")
	builder.WriteString("func (resolver *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{resolver} }\n\n")

	builder.WriteString("func (resolver *queryResolver) ContentTypes(ctx context.Context) ([]map[string]interface{}, error) {\n")
	builder.WriteString("\tcontentTypes, err := resolver.ctUC.FindAll(ctx)\n")
	builder.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
	builder.WriteString("\tresult := make([]map[string]interface{}, len(contentTypes))\n")
	builder.WriteString("\tfor idx, contentType := range contentTypes {\n")
	builder.WriteString("\t\tresult[idx] = map[string]interface{}{\n")
	builder.WriteString("\t\t\t\"id\": contentType.ID, \"name\": contentType.Name, \"slug\": contentType.Slug,\n")
	builder.WriteString("\t\t\t\"kind\": string(contentType.Kind), \"createdAt\": contentType.CreatedAt, \"updatedAt\": contentType.UpdatedAt,\n")
	builder.WriteString("\t\t}\n")
	builder.WriteString("\t}\n")
	builder.WriteString("\treturn result, nil\n")
	builder.WriteString("}\n\n")

	builder.WriteString("func (resolver *mutationResolver) Empty(_ context.Context) (*bool, error) {\n")
	builder.WriteString("\treturn nil, nil\n")
	builder.WriteString("}\n\n")
}

func writeFieldDefinitions(builder *strings.Builder, def contenttype.ContentTypeDefinition) {
	varName := slugToCamelCase(def.Slug) + "Fields"
	fmt.Fprintf(builder, "var %s = []entity.FieldDefinition{\n", varName)
	writeFieldSlice(builder, def.Fields, 1)
	builder.WriteString("}\n")
}

func writeFieldSlice(builder *strings.Builder, fields []entity.FieldDefinition, depth int) {
	indent := strings.Repeat("\t", depth)
	for _, field := range fields {
		fmt.Fprintf(builder, "%s{Name: %q, Type: %q", indent, field.Name, field.Type)
		if field.Repeatable {
			builder.WriteString(", Repeatable: true")
		}
		if len(field.Fields) > 0 {
			builder.WriteString(", Fields: []entity.FieldDefinition{\n")
			writeFieldSlice(builder, field.Fields, depth+1)
			fmt.Fprintf(builder, "%s}", indent)
		}
		builder.WriteString("},\n")
	}
}

func writeCollectionResolvers(builder *strings.Builder, def contenttype.ContentTypeDefinition) {
	pascal := slugToPascalCase(def.Slug)
	camel := slugToCamelCase(def.Slug)
	fieldsVar := camel + "Fields"

	fmt.Fprintf(builder, "func (resolver *queryResolver) %s(ctx context.Context, %sID string, locale *string, status *string) (map[string]interface{}, error) {\n", pascal, camel)
	fmt.Fprintf(builder, "\treturn resolver.getDocument(ctx, %q, %sID, locale, status, %s)\n", def.Slug, camel, fieldsVar)
	builder.WriteString("}\n\n")

	fmt.Fprintf(builder, "func (resolver *queryResolver) %s(ctx context.Context, filters []*model.%sFilter, orderBy *model.%sOrderBy, start *int, size *int, locale *string, status *string) ([]map[string]interface{}, error) {\n", pluralize(pascal), pascal, pascal)
	fmt.Fprintf(builder, "\treturn resolver.getDocumentList(ctx, %q, filters, orderBy, start, size, locale, status, %s)\n", def.Slug, fieldsVar)
	builder.WriteString("}\n\n")

	fmt.Fprintf(builder, "func (resolver *mutationResolver) Create%s(ctx context.Context, data model.%sInput) (map[string]interface{}, error) {\n", pascal, pascal)
	fmt.Fprintf(builder, "\treturn resolver.createDocument(ctx, %q, data, %s)\n", def.Slug, fieldsVar)
	builder.WriteString("}\n\n")

	fmt.Fprintf(builder, "func (resolver *mutationResolver) Update%s(ctx context.Context, %sID string, data model.%sInput) (map[string]interface{}, error) {\n", pascal, camel, pascal)
	fmt.Fprintf(builder, "\treturn resolver.updateDocument(ctx, %q, %sID, data, %s)\n", def.Slug, camel, fieldsVar)
	builder.WriteString("}\n\n")

	fmt.Fprintf(builder, "func (resolver *mutationResolver) Delete%s(ctx context.Context, %sID string) (bool, error) {\n", pascal, camel)
	fmt.Fprintf(builder, "\treturn resolver.deleteDocument(ctx, %q, %sID, %s)\n", def.Slug, camel, fieldsVar)
	builder.WriteString("}\n\n")

	fmt.Fprintf(builder, "func (resolver *mutationResolver) Publish%s(ctx context.Context, %sID string, locale *string) (map[string]interface{}, error) {\n", pascal, camel)
	fmt.Fprintf(builder, "\treturn resolver.publishDocument(ctx, %q, %sID, locale, %s)\n", def.Slug, camel, fieldsVar)
	builder.WriteString("}\n\n")

	fmt.Fprintf(builder, "func (resolver *mutationResolver) Unpublish%s(ctx context.Context, %sID string, locale *string) (map[string]interface{}, error) {\n", pascal, camel)
	fmt.Fprintf(builder, "\treturn resolver.unpublishDocument(ctx, %q, %sID, locale, %s)\n", def.Slug, camel, fieldsVar)
	builder.WriteString("}\n")
}

func writeSingleResolvers(builder *strings.Builder, def contenttype.ContentTypeDefinition) {
	pascal := slugToPascalCase(def.Slug)
	camel := slugToCamelCase(def.Slug)
	fieldsVar := camel + "Fields"

	fmt.Fprintf(builder, "func (resolver *queryResolver) %s(ctx context.Context, locale *string, status *string) (map[string]interface{}, error) {\n", pascal)
	fmt.Fprintf(builder, "\treturn resolver.getSingleType(ctx, %q, locale, status, %s)\n", def.Slug, fieldsVar)
	builder.WriteString("}\n\n")

	fmt.Fprintf(builder, "func (resolver *mutationResolver) Save%s(ctx context.Context, data model.%sInput, locale *string) (map[string]interface{}, error) {\n", pascal, pascal)
	fmt.Fprintf(builder, "\treturn resolver.saveSingleType(ctx, %q, data, locale, %s)\n", def.Slug, fieldsVar)
	builder.WriteString("}\n\n")

	fmt.Fprintf(builder, "func (resolver *mutationResolver) Publish%s(ctx context.Context, locale *string) (map[string]interface{}, error) {\n", pascal)
	fmt.Fprintf(builder, "\treturn resolver.publishSingleType(ctx, %q, locale, %s)\n", def.Slug, fieldsVar)
	builder.WriteString("}\n\n")

	fmt.Fprintf(builder, "func (resolver *mutationResolver) Unpublish%s(ctx context.Context, locale *string) (map[string]interface{}, error) {\n", pascal)
	fmt.Fprintf(builder, "\treturn resolver.unpublishSingleType(ctx, %q, locale, %s)\n", def.Slug, fieldsVar)
	builder.WriteString("}\n")
}

// ── ResolverRoot + Map Field Resolvers ──

type mapField struct {
	Name     string
	GoType   string
	Nullable bool
	MapKey   string
}

func writeResolverRootMethods(builder *strings.Builder, defs []contenttype.ContentTypeDefinition) {
	builder.WriteString("// ── ResolverRoot methods ──\n\n")

	builder.WriteString("type mediaAssetFieldResolver struct{ *Resolver }\n")
	builder.WriteString("type contentTypeFieldResolver struct{ *Resolver }\n\n")

	builder.WriteString("func (resolver *Resolver) MediaAsset() generated.MediaAssetResolver { return &mediaAssetFieldResolver{resolver} }\n")
	builder.WriteString("func (resolver *Resolver) ContentType() generated.ContentTypeResolver { return &contentTypeFieldResolver{resolver} }\n\n")

	for _, def := range defs {
		pascal := slugToPascalCase(def.Slug)
		lower := slugToCamelCase(def.Slug)
		resolverType := lower + "FieldResolver"
		fmt.Fprintf(builder, "type %s struct{ *Resolver }\n", resolverType)
		fmt.Fprintf(builder, "func (resolver *Resolver) %s() generated.%sResolver { return &%s{resolver} }\n\n", pascal, pascal, resolverType)

		writeComponentResolverRootMethods(builder, pascal, def.Fields)
	}
}

func writeComponentResolverRootMethods(builder *strings.Builder, parentType string, fields []entity.FieldDefinition) {
	for _, field := range fields {
		if field.Type != "component" {
			continue
		}
		compType := parentType + slugToPascalCase(field.Name)
		lower := toLowerFirst(compType)
		resolverType := lower + "FieldResolver"
		fmt.Fprintf(builder, "type %s struct{ *Resolver }\n", resolverType)
		fmt.Fprintf(builder, "func (resolver *Resolver) %s() generated.%sResolver { return &%s{resolver} }\n\n", compType, compType, resolverType)

		writeComponentResolverRootMethods(builder, compType, field.Fields)
	}
}

func writeMapFieldResolvers(builder *strings.Builder, defs []contenttype.ContentTypeDefinition) {
	builder.WriteString("// ── Map field resolvers ──\n\n")

	writeMapFieldResolverMethods(builder, "mediaAssetFieldResolver", []mapField{
		{Name: "DocumentID", GoType: "string", Nullable: false, MapKey: "documentId"},
		{Name: "URL", GoType: "string", Nullable: false, MapKey: "url"},
		{Name: "ThumbnailURL", GoType: "string", Nullable: true, MapKey: "thumbnailUrl"},
		{Name: "FileName", GoType: "string", Nullable: true, MapKey: "fileName"},
		{Name: "Width", GoType: "int", Nullable: true, MapKey: "width"},
		{Name: "Height", GoType: "int", Nullable: true, MapKey: "height"},
	})

	writeMapFieldResolverMethods(builder, "contentTypeFieldResolver", []mapField{
		{Name: "ID", GoType: "string", Nullable: false, MapKey: "id"},
		{Name: "Name", GoType: "string", Nullable: false, MapKey: "name"},
		{Name: "Slug", GoType: "string", Nullable: false, MapKey: "slug"},
		{Name: "Kind", GoType: "string", Nullable: false, MapKey: "kind"},
		{Name: "CreatedAt", GoType: "time.Time", Nullable: true, MapKey: "createdAt"},
		{Name: "UpdatedAt", GoType: "time.Time", Nullable: true, MapKey: "updatedAt"},
	})

	for _, def := range defs {
		pascal := slugToPascalCase(def.Slug)
		lower := slugToCamelCase(def.Slug)
		resolverType := lower + "FieldResolver"

		docFields := buildDocumentMapFields(def.Fields)
		writeMapFieldResolverMethods(builder, resolverType, docFields)

		writeComponentFieldResolvers(builder, pascal, def.Fields)
	}
}

func writeComponentFieldResolvers(builder *strings.Builder, parentType string, fields []entity.FieldDefinition) {
	for _, field := range fields {
		if field.Type != "component" {
			continue
		}
		compType := parentType + slugToPascalCase(field.Name)
		lower := toLowerFirst(compType)
		resolverType := lower + "FieldResolver"

		compFields := buildComponentMapFields(field.Fields)
		writeMapFieldResolverMethods(builder, resolverType, compFields)

		writeComponentFieldResolvers(builder, compType, field.Fields)
	}
}

func buildDocumentMapFields(fields []entity.FieldDefinition) []mapField {
	result := []mapField{
		{Name: "DocumentID", GoType: "string", Nullable: false, MapKey: "documentId"},
	}
	for _, field := range fields {
		result = append(result, fieldToMapField(field))
	}
	result = append(result,
		mapField{Name: "Locale", GoType: "string", Nullable: false, MapKey: "locale"},
		mapField{Name: "CreatedAt", GoType: "time.Time", Nullable: false, MapKey: "createdAt"},
		mapField{Name: "UpdatedAt", GoType: "time.Time", Nullable: false, MapKey: "updatedAt"},
		mapField{Name: "PublishedAt", GoType: "time.Time", Nullable: true, MapKey: "publishedAt"},
	)
	return result
}

func buildComponentMapFields(fields []entity.FieldDefinition) []mapField {
	var result []mapField
	for _, field := range fields {
		result = append(result, fieldToMapField(field))
	}
	return result
}

func fieldToMapField(field entity.FieldDefinition) mapField {
	name := slugToPascalCase(field.Name)
	switch field.Type {
	case "text", "richtext":
		return mapField{Name: name, GoType: "string", Nullable: true, MapKey: field.Name}
	case "number":
		return mapField{Name: name, GoType: "float64", Nullable: true, MapKey: field.Name}
	case "boolean":
		return mapField{Name: name, GoType: "bool", Nullable: true, MapKey: field.Name}
	case "media":
		return mapField{Name: name, GoType: "map[string]interface{}", Nullable: true, MapKey: field.Name}
	case "json":
		return mapField{Name: name, GoType: "map[string]interface{}", Nullable: true, MapKey: field.Name}
	case "component":
		if field.Repeatable {
			return mapField{Name: name, GoType: "[]map[string]interface{}", Nullable: true, MapKey: field.Name}
		}
		return mapField{Name: name, GoType: "map[string]interface{}", Nullable: true, MapKey: field.Name}
	default:
		return mapField{Name: name, GoType: "string", Nullable: true, MapKey: field.Name}
	}
}

func writeMapFieldResolverMethods(builder *strings.Builder, resolverType string, fields []mapField) {
	for _, field := range fields {
		writeMapFieldMethod(builder, resolverType, field)
	}
	builder.WriteString("\n")
}

func writeMapFieldMethod(builder *strings.Builder, resolverType string, field mapField) {
	goReturnType := resolveReturnType(field)

	fmt.Fprintf(builder, "func (resolver *%s) %s(_ context.Context, obj map[string]interface{}) (%s, error) {\n", resolverType, field.Name, goReturnType)

	writeFieldExtractor(builder, field)

	builder.WriteString("}\n\n")
}

func resolveReturnType(field mapField) string {
	switch field.GoType {
	case "time.Time":
		return "*time.Time"
	case "map[string]interface{}":
		return "map[string]interface{}"
	case "[]map[string]interface{}":
		return "[]map[string]interface{}"
	default:
		if field.Nullable {
			return "*" + field.GoType
		}
		return field.GoType
	}
}

func writeFieldExtractor(builder *strings.Builder, field mapField) {
	switch field.GoType {
	case "string":
		if field.Nullable {
			fmt.Fprintf(builder, "\tval, exists := obj[%q].(string)\n", field.MapKey)
			builder.WriteString("\tif !exists {\n\t\treturn nil, nil\n\t}\n")
			builder.WriteString("\treturn &val, nil\n")
		} else {
			fmt.Fprintf(builder, "\tval, _ := obj[%q].(string)\n", field.MapKey)
			builder.WriteString("\treturn val, nil\n")
		}
	case "float64":
		fmt.Fprintf(builder, "\tswitch val := obj[%q].(type) {\n", field.MapKey)
		builder.WriteString("\tcase float64:\n")
		builder.WriteString("\t\treturn &val, nil\n")
		builder.WriteString("\tcase int:\n")
		builder.WriteString("\t\tcasted := float64(val)\n")
		builder.WriteString("\t\treturn &casted, nil\n")
		builder.WriteString("\tdefault:\n")
		builder.WriteString("\t\treturn nil, nil\n")
		builder.WriteString("\t}\n")
	case "bool":
		fmt.Fprintf(builder, "\tval, exists := obj[%q].(bool)\n", field.MapKey)
		builder.WriteString("\tif !exists {\n\t\treturn nil, nil\n\t}\n")
		builder.WriteString("\treturn &val, nil\n")
	case "int":
		fmt.Fprintf(builder, "\tswitch val := obj[%q].(type) {\n", field.MapKey)
		builder.WriteString("\tcase int:\n")
		builder.WriteString("\t\treturn &val, nil\n")
		builder.WriteString("\tcase float64:\n")
		builder.WriteString("\t\tcasted := int(val)\n")
		builder.WriteString("\t\treturn &casted, nil\n")
		builder.WriteString("\tdefault:\n")
		builder.WriteString("\t\treturn nil, nil\n")
		builder.WriteString("\t}\n")
	case "time.Time":
		fmt.Fprintf(builder, "\tswitch val := obj[%q].(type) {\n", field.MapKey)
		builder.WriteString("\tcase time.Time:\n")
		builder.WriteString("\t\treturn &val, nil\n")
		builder.WriteString("\tcase *time.Time:\n")
		builder.WriteString("\t\treturn val, nil\n")
		builder.WriteString("\tdefault:\n")
		builder.WriteString("\t\treturn nil, nil\n")
		builder.WriteString("\t}\n")
	case "map[string]interface{}":
		fmt.Fprintf(builder, "\tval, _ := obj[%q].(map[string]interface{})\n", field.MapKey)
		builder.WriteString("\treturn val, nil\n")
	case "[]map[string]interface{}":
		fmt.Fprintf(builder, "\traw, _ := obj[%q].([]interface{})\n", field.MapKey)
		builder.WriteString("\tif raw == nil {\n\t\treturn nil, nil\n\t}\n")
		builder.WriteString("\tresult := make([]map[string]interface{}, 0, len(raw))\n")
		builder.WriteString("\tfor _, item := range raw {\n")
		builder.WriteString("\t\tif itemMap, isMap := item.(map[string]interface{}); isMap {\n")
		builder.WriteString("\t\t\tresult = append(result, itemMap)\n")
		builder.WriteString("\t\t}\n")
		builder.WriteString("\t}\n")
		builder.WriteString("\treturn result, nil\n")
	default:
		fmt.Fprintf(builder, "\tval, _ := obj[%q].(%s)\n", field.MapKey, field.GoType)
		if field.Nullable {
			builder.WriteString("\treturn &val, nil\n")
		} else {
			builder.WriteString("\treturn val, nil\n")
		}
	}
}

func toLowerFirst(name string) string {
	if len(name) == 0 {
		return name
	}
	return strings.ToLower(name[:1]) + name[1:]
}

// ── gqlgen.yml Model Injection ──

func injectModels(graphqlDir string, defs []contenttype.ContentTypeDefinition) error {
	ymlPath := filepath.Join(graphqlDir, "gqlgen.yml")
	data, err := os.ReadFile(ymlPath)
	if err != nil {
		return fmt.Errorf("read gqlgen.yml: %w", err)
	}

	content := string(data)
	marker := "# --- gqlcodegen models start ---"
	endMarker := "# --- gqlcodegen models end ---"

	if idx := strings.Index(content, marker); idx >= 0 {
		endIdx := strings.Index(content, endMarker)
		if endIdx >= 0 {
			content = strings.TrimRight(content[:idx], " \n") + "\n"
		}
	}

	content = strings.TrimRight(content, "\n") + "\n"

	var models strings.Builder
	models.WriteString("  " + marker + "\n")

	models.WriteString("  MediaAsset:\n")
	models.WriteString("    model: \"project-abyssoftime-cms-v2/api/graphql/model.MediaAssetMap\"\n")
	models.WriteString("  ContentType:\n")
	models.WriteString("    model: \"project-abyssoftime-cms-v2/api/graphql/model.ContentTypeMap\"\n")

	for _, def := range defs {
		pascal := slugToPascalCase(def.Slug)
		fmt.Fprintf(&models, "  %s:\n", pascal)
		models.WriteString("    model: \"project-abyssoftime-cms-v2/api/graphql/model.DocumentMap\"\n")

		collectComponentTypes(&models, pascal, def.Fields)
	}
	models.WriteString("  " + endMarker + "\n")

	content += models.String()

	return os.WriteFile(ymlPath, []byte(content), 0o644)
}

func collectComponentTypes(builder *strings.Builder, parentType string, fields []entity.FieldDefinition) {
	for _, field := range fields {
		if field.Type != "component" {
			continue
		}
		compType := parentType + slugToPascalCase(field.Name)
		fmt.Fprintf(builder, "  %s:\n", compType)
		builder.WriteString("    model: \"project-abyssoftime-cms-v2/api/graphql/model.DocumentMap\"\n")
		collectComponentTypes(builder, compType, field.Fields)
	}
}

// ── Naming helpers ──

func slugToPascalCase(slug string) string {
	parts := strings.Split(slug, "-")
	for idx, part := range parts {
		if len(part) > 0 {
			parts[idx] = strings.ToUpper(part[:1]) + part[1:]
		}
	}
	return strings.Join(parts, "")
}

func slugToCamelCase(slug string) string {
	pascal := slugToPascalCase(slug)
	if len(pascal) == 0 {
		return ""
	}
	return strings.ToLower(pascal[:1]) + pascal[1:]
}

func pluralize(name string) string {
	if len(name) == 0 {
		return name
	}
	lower := strings.ToLower(name)
	if strings.HasSuffix(lower, "s") || strings.HasSuffix(lower, "x") || strings.HasSuffix(lower, "z") || strings.HasSuffix(lower, "ch") || strings.HasSuffix(lower, "sh") {
		return name + "es"
	}
	return name + "s"
}

func fieldTypeToGraphQL(fieldType string) string {
	switch fieldType {
	case "text", "richtext":
		return "String"
	case "number":
		return "Float"
	case "boolean":
		return "Boolean"
	case "media":
		return "MediaAsset"
	case "json":
		return "JSON"
	default:
		return "String"
	}
}

func fieldTypeToInputGraphQL(fieldType string) string {
	switch fieldType {
	case "text", "richtext":
		return "String"
	case "number":
		return "Float"
	case "boolean":
		return "Boolean"
	case "media":
		return "String"
	case "json":
		return "JSON"
	default:
		return "String"
	}
}
