// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/cms/v1/content_type.proto

package cmsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FieldDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Ext           []string               `protobuf:"bytes,3,rep,name=ext,proto3" json:"ext,omitempty"`
	Fields        []*FieldDefinition     `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldDefinition) Reset() {
	*x = FieldDefinition{}
	mi := &file_proto_cms_v1_content_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldDefinition) ProtoMessage() {}

func (x *FieldDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cms_v1_content_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldDefinition.ProtoReflect.Descriptor instead.
func (*FieldDefinition) Descriptor() ([]byte, []int) {
	return file_proto_cms_v1_content_type_proto_rawDescGZIP(), []int{0}
}

func (x *FieldDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FieldDefinition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FieldDefinition) GetExt() []string {
	if x != nil {
		return x.Ext
	}
	return nil
}

func (x *FieldDefinition) GetFields() []*FieldDefinition {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ContentType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Kind          string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	Fields        []*FieldDefinition     `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty"`
	ListFields    []string               `protobuf:"bytes,6,rep,name=list_fields,json=listFields,proto3" json:"list_fields,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentType) Reset() {
	*x = ContentType{}
	mi := &file_proto_cms_v1_content_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentType) ProtoMessage() {}

func (x *ContentType) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cms_v1_content_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentType.ProtoReflect.Descriptor instead.
func (*ContentType) Descriptor() ([]byte, []int) {
	return file_proto_cms_v1_content_type_proto_rawDescGZIP(), []int{1}
}

func (x *ContentType) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContentType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContentType) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ContentType) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ContentType) GetFields() []*FieldDefinition {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *ContentType) GetListFields() []string {
	if x != nil {
		return x.ListFields
	}
	return nil
}

func (x *ContentType) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ContentType) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetContentTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentTypeRequest) Reset() {
	*x = GetContentTypeRequest{}
	mi := &file_proto_cms_v1_content_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentTypeRequest) ProtoMessage() {}

func (x *GetContentTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cms_v1_content_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentTypeRequest.ProtoReflect.Descriptor instead.
func (*GetContentTypeRequest) Descriptor() ([]byte, []int) {
	return file_proto_cms_v1_content_type_proto_rawDescGZIP(), []int{2}
}

func (x *GetContentTypeRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type ListContentTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContentTypesRequest) Reset() {
	*x = ListContentTypesRequest{}
	mi := &file_proto_cms_v1_content_type_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContentTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContentTypesRequest) ProtoMessage() {}

func (x *ListContentTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cms_v1_content_type_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContentTypesRequest.ProtoReflect.Descriptor instead.
func (*ListContentTypesRequest) Descriptor() ([]byte, []int) {
	return file_proto_cms_v1_content_type_proto_rawDescGZIP(), []int{3}
}

type ListContentTypesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentTypes  []*ContentType         `protobuf:"bytes,1,rep,name=content_types,json=contentTypes,proto3" json:"content_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContentTypesResponse) Reset() {
	*x = ListContentTypesResponse{}
	mi := &file_proto_cms_v1_content_type_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContentTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContentTypesResponse) ProtoMessage() {}

func (x *ListContentTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cms_v1_content_type_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContentTypesResponse.ProtoReflect.Descriptor instead.
func (*ListContentTypesResponse) Descriptor() ([]byte, []int) {
	return file_proto_cms_v1_content_type_proto_rawDescGZIP(), []int{4}
}

func (x *ListContentTypesResponse) GetContentTypes() []*ContentType {
	if x != nil {
		return x.ContentTypes
	}
	return nil
}

var File_proto_cms_v1_content_type_proto protoreflect.FileDescriptor

const file_proto_cms_v1_content_type_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/cms/v1/content_type.proto\x12\x06cms.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"|\n" +
	"\x0fFieldDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x10\n" +
	"\x03ext\x18\x03 \x03(\tR\x03ext\x12/\n" +
	"\x06fields\x18\x04 \x03(\v2\x17.cms.v1.FieldDefinitionR\x06fields\"\xa1\x02\n" +
	"\vContentType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12/\n" +
	"\x06fields\x18\x05 \x03(\v2\x17.cms.v1.FieldDefinitionR\x06fields\x12\x1f\n" +
	"\vlist_fields\x18\x06 \x03(\tR\n" +
	"listFields\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"+\n" +
	"\x15GetContentTypeRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\"\x19\n" +
	"\x17ListContentTypesRequest\"T\n" +
	"\x18ListContentTypesResponse\x128\n" +
	"\rcontent_types\x18\x01 \x03(\v2\x13.cms.v1.ContentTypeR\fcontentTypes2\xb1\x01\n" +
	"\x12ContentTypeService\x12D\n" +
	"\x0eGetContentType\x12\x1d.cms.v1.GetContentTypeRequest\x1a\x13.cms.v1.ContentType\x12U\n" +
	"\x10ListContentTypes\x12\x1f.cms.v1.ListContentTypesRequest\x1a .cms.v1.ListContentTypesResponseB3Z1project-abyssoftime-cms-v2/api/proto/cms/v1;cmsv1b\x06proto3"

var (
	file_proto_cms_v1_content_type_proto_rawDescOnce sync.Once
	file_proto_cms_v1_content_type_proto_rawDescData []byte
)

func file_proto_cms_v1_content_type_proto_rawDescGZIP() []byte {
	file_proto_cms_v1_content_type_proto_rawDescOnce.Do(func() {
		file_proto_cms_v1_content_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cms_v1_content_type_proto_rawDesc), len(file_proto_cms_v1_content_type_proto_rawDesc)))
	})
	return file_proto_cms_v1_content_type_proto_rawDescData
}

var file_proto_cms_v1_content_type_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_cms_v1_content_type_proto_goTypes = []any{
	(*FieldDefinition)(nil),          // 0: cms.v1.FieldDefinition
	(*ContentType)(nil),              // 1: cms.v1.ContentType
	(*GetContentTypeRequest)(nil),    // 2: cms.v1.GetContentTypeRequest
	(*ListContentTypesRequest)(nil),  // 3: cms.v1.ListContentTypesRequest
	(*ListContentTypesResponse)(nil), // 4: cms.v1.ListContentTypesResponse
	(*timestamppb.Timestamp)(nil),    // 5: google.protobuf.Timestamp
}
var file_proto_cms_v1_content_type_proto_depIdxs = []int32{
	0, // 0: cms.v1.FieldDefinition.fields:type_name -> cms.v1.FieldDefinition
	0, // 1: cms.v1.ContentType.fields:type_name -> cms.v1.FieldDefinition
	5, // 2: cms.v1.ContentType.created_at:type_name -> google.protobuf.Timestamp
	5, // 3: cms.v1.ContentType.updated_at:type_name -> google.protobuf.Timestamp
	1, // 4: cms.v1.ListContentTypesResponse.content_types:type_name -> cms.v1.ContentType
	2, // 5: cms.v1.ContentTypeService.GetContentType:input_type -> cms.v1.GetContentTypeRequest
	3, // 6: cms.v1.ContentTypeService.ListContentTypes:input_type -> cms.v1.ListContentTypesRequest
	1, // 7: cms.v1.ContentTypeService.GetContentType:output_type -> cms.v1.ContentType
	4, // 8: cms.v1.ContentTypeService.ListContentTypes:output_type -> cms.v1.ListContentTypesResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_cms_v1_content_type_proto_init() }
func file_proto_cms_v1_content_type_proto_init() {
	if File_proto_cms_v1_content_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cms_v1_content_type_proto_rawDesc), len(file_proto_cms_v1_content_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cms_v1_content_type_proto_goTypes,
		DependencyIndexes: file_proto_cms_v1_content_type_proto_depIdxs,
		MessageInfos:      file_proto_cms_v1_content_type_proto_msgTypes,
	}.Build()
	File_proto_cms_v1_content_type_proto = out.File
	file_proto_cms_v1_content_type_proto_goTypes = nil
	file_proto_cms_v1_content_type_proto_depIdxs = nil
}
