// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/cms/v1/content_type.proto

package cmsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ContentTypeService_GetContentType_FullMethodName   = "/cms.v1.ContentTypeService/GetContentType"
	ContentTypeService_ListContentTypes_FullMethodName = "/cms.v1.ContentTypeService/ListContentTypes"
)

// ContentTypeServiceClient is the client API for ContentTypeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContentTypeServiceClient interface {
	GetContentType(ctx context.Context, in *GetContentTypeRequest, opts ...grpc.CallOption) (*ContentType, error)
	ListContentTypes(ctx context.Context, in *ListContentTypesRequest, opts ...grpc.CallOption) (*ListContentTypesResponse, error)
}

type contentTypeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewContentTypeServiceClient(cc grpc.ClientConnInterface) ContentTypeServiceClient {
	return &contentTypeServiceClient{cc}
}

func (c *contentTypeServiceClient) GetContentType(ctx context.Context, in *GetContentTypeRequest, opts ...grpc.CallOption) (*ContentType, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContentType)
	err := c.cc.Invoke(ctx, ContentTypeService_GetContentType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentTypeServiceClient) ListContentTypes(ctx context.Context, in *ListContentTypesRequest, opts ...grpc.CallOption) (*ListContentTypesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListContentTypesResponse)
	err := c.cc.Invoke(ctx, ContentTypeService_ListContentTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContentTypeServiceServer is the server API for ContentTypeService service.
// All implementations must embed UnimplementedContentTypeServiceServer
// for forward compatibility.
type ContentTypeServiceServer interface {
	GetContentType(context.Context, *GetContentTypeRequest) (*ContentType, error)
	ListContentTypes(context.Context, *ListContentTypesRequest) (*ListContentTypesResponse, error)
	mustEmbedUnimplementedContentTypeServiceServer()
}

// UnimplementedContentTypeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContentTypeServiceServer struct{}

func (UnimplementedContentTypeServiceServer) GetContentType(context.Context, *GetContentTypeRequest) (*ContentType, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContentType not implemented")
}
func (UnimplementedContentTypeServiceServer) ListContentTypes(context.Context, *ListContentTypesRequest) (*ListContentTypesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListContentTypes not implemented")
}
func (UnimplementedContentTypeServiceServer) mustEmbedUnimplementedContentTypeServiceServer() {}
func (UnimplementedContentTypeServiceServer) testEmbeddedByValue()                            {}

// UnsafeContentTypeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContentTypeServiceServer will
// result in compilation errors.
type UnsafeContentTypeServiceServer interface {
	mustEmbedUnimplementedContentTypeServiceServer()
}

func RegisterContentTypeServiceServer(s grpc.ServiceRegistrar, srv ContentTypeServiceServer) {
	// If the following call panics, it indicates UnimplementedContentTypeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContentTypeService_ServiceDesc, srv)
}

func _ContentTypeService_GetContentType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContentTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentTypeServiceServer).GetContentType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentTypeService_GetContentType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentTypeServiceServer).GetContentType(ctx, req.(*GetContentTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentTypeService_ListContentTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListContentTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentTypeServiceServer).ListContentTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentTypeService_ListContentTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentTypeServiceServer).ListContentTypes(ctx, req.(*ListContentTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContentTypeService_ServiceDesc is the grpc.ServiceDesc for ContentTypeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContentTypeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cms.v1.ContentTypeService",
	HandlerType: (*ContentTypeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetContentType",
			Handler:    _ContentTypeService_GetContentType_Handler,
		},
		{
			MethodName: "ListContentTypes",
			Handler:    _ContentTypeService_ListContentTypes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/cms/v1/content_type.proto",
}
