// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/cms/v1/document.proto

package cmsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	ContentTypeId string                 `protobuf:"bytes,3,opt,name=content_type_id,json=contentTypeId,proto3" json:"content_type_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Locale        string                 `protobuf:"bytes,5,opt,name=locale,proto3" json:"locale,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	PublishedAt   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,9,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,10,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	PublishedBy   string                 `protobuf:"bytes,11,opt,name=published_by,json=publishedBy,proto3" json:"published_by,omitempty"`
	Status        string                 `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_proto_cms_v1_document_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cms_v1_document_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_proto_cms_v1_document_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *Document) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Document) GetContentTypeId() string {
	if x != nil {
		return x.ContentTypeId
	}
	return ""
}

func (x *Document) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Document) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *Document) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Document) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Document) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *Document) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Document) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *Document) GetPublishedBy() string {
	if x != nil {
		return x.PublishedBy
	}
	return ""
}

func (x *Document) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetDocumentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContentTypeSlug string                 `protobuf:"bytes,1,opt,name=content_type_slug,json=contentTypeSlug,proto3" json:"content_type_slug,omitempty"`
	DocumentId      string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Locale          string                 `protobuf:"bytes,3,opt,name=locale,proto3" json:"locale,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetDocumentRequest) Reset() {
	*x = GetDocumentRequest{}
	mi := &file_proto_cms_v1_document_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentRequest) ProtoMessage() {}

func (x *GetDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cms_v1_document_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentRequest) Descriptor() ([]byte, []int) {
	return file_proto_cms_v1_document_proto_rawDescGZIP(), []int{1}
}

func (x *GetDocumentRequest) GetContentTypeSlug() string {
	if x != nil {
		return x.ContentTypeSlug
	}
	return ""
}

func (x *GetDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *GetDocumentRequest) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

type ListDocumentsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContentTypeSlug string                 `protobuf:"bytes,1,opt,name=content_type_slug,json=contentTypeSlug,proto3" json:"content_type_slug,omitempty"`
	Start           int32                  `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	Size            int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Locale          string                 `protobuf:"bytes,4,opt,name=locale,proto3" json:"locale,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListDocumentsRequest) Reset() {
	*x = ListDocumentsRequest{}
	mi := &file_proto_cms_v1_document_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsRequest) ProtoMessage() {}

func (x *ListDocumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cms_v1_document_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsRequest.ProtoReflect.Descriptor instead.
func (*ListDocumentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_cms_v1_document_proto_rawDescGZIP(), []int{2}
}

func (x *ListDocumentsRequest) GetContentTypeSlug() string {
	if x != nil {
		return x.ContentTypeSlug
	}
	return ""
}

func (x *ListDocumentsRequest) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *ListDocumentsRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListDocumentsRequest) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

type ListDocumentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Document            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Start         int32                  `protobuf:"varint,3,opt,name=start,proto3" json:"start,omitempty"`
	Size          int32                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentsResponse) Reset() {
	*x = ListDocumentsResponse{}
	mi := &file_proto_cms_v1_document_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsResponse) ProtoMessage() {}

func (x *ListDocumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cms_v1_document_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsResponse.ProtoReflect.Descriptor instead.
func (*ListDocumentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_cms_v1_document_proto_rawDescGZIP(), []int{3}
}

func (x *ListDocumentsResponse) GetItems() []*Document {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListDocumentsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListDocumentsResponse) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *ListDocumentsResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type SaveDocumentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContentTypeSlug string                 `protobuf:"bytes,1,opt,name=content_type_slug,json=contentTypeSlug,proto3" json:"content_type_slug,omitempty"`
	DocumentId      string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Data            []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Locale          string                 `protobuf:"bytes,4,opt,name=locale,proto3" json:"locale,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SaveDocumentRequest) Reset() {
	*x = SaveDocumentRequest{}
	mi := &file_proto_cms_v1_document_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveDocumentRequest) ProtoMessage() {}

func (x *SaveDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cms_v1_document_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveDocumentRequest.ProtoReflect.Descriptor instead.
func (*SaveDocumentRequest) Descriptor() ([]byte, []int) {
	return file_proto_cms_v1_document_proto_rawDescGZIP(), []int{4}
}

func (x *SaveDocumentRequest) GetContentTypeSlug() string {
	if x != nil {
		return x.ContentTypeSlug
	}
	return ""
}

func (x *SaveDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *SaveDocumentRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SaveDocumentRequest) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

type PublishDocumentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContentTypeSlug string                 `protobuf:"bytes,1,opt,name=content_type_slug,json=contentTypeSlug,proto3" json:"content_type_slug,omitempty"`
	DocumentId      string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Locale          string                 `protobuf:"bytes,3,opt,name=locale,proto3" json:"locale,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PublishDocumentRequest) Reset() {
	*x = PublishDocumentRequest{}
	mi := &file_proto_cms_v1_document_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishDocumentRequest) ProtoMessage() {}

func (x *PublishDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cms_v1_document_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishDocumentRequest.ProtoReflect.Descriptor instead.
func (*PublishDocumentRequest) Descriptor() ([]byte, []int) {
	return file_proto_cms_v1_document_proto_rawDescGZIP(), []int{5}
}

func (x *PublishDocumentRequest) GetContentTypeSlug() string {
	if x != nil {
		return x.ContentTypeSlug
	}
	return ""
}

func (x *PublishDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *PublishDocumentRequest) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

type DeleteDocumentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContentTypeSlug string                 `protobuf:"bytes,1,opt,name=content_type_slug,json=contentTypeSlug,proto3" json:"content_type_slug,omitempty"`
	DocumentId      string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteDocumentRequest) Reset() {
	*x = DeleteDocumentRequest{}
	mi := &file_proto_cms_v1_document_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentRequest) ProtoMessage() {}

func (x *DeleteDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cms_v1_document_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentRequest.ProtoReflect.Descriptor instead.
func (*DeleteDocumentRequest) Descriptor() ([]byte, []int) {
	return file_proto_cms_v1_document_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteDocumentRequest) GetContentTypeSlug() string {
	if x != nil {
		return x.ContentTypeSlug
	}
	return ""
}

func (x *DeleteDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

type DeleteDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentResponse) Reset() {
	*x = DeleteDocumentResponse{}
	mi := &file_proto_cms_v1_document_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentResponse) ProtoMessage() {}

func (x *DeleteDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cms_v1_document_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentResponse.ProtoReflect.Descriptor instead.
func (*DeleteDocumentResponse) Descriptor() ([]byte, []int) {
	return file_proto_cms_v1_document_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteDocumentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetSingleTypeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContentTypeSlug string                 `protobuf:"bytes,1,opt,name=content_type_slug,json=contentTypeSlug,proto3" json:"content_type_slug,omitempty"`
	Locale          string                 `protobuf:"bytes,2,opt,name=locale,proto3" json:"locale,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetSingleTypeRequest) Reset() {
	*x = GetSingleTypeRequest{}
	mi := &file_proto_cms_v1_document_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSingleTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSingleTypeRequest) ProtoMessage() {}

func (x *GetSingleTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cms_v1_document_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSingleTypeRequest.ProtoReflect.Descriptor instead.
func (*GetSingleTypeRequest) Descriptor() ([]byte, []int) {
	return file_proto_cms_v1_document_proto_rawDescGZIP(), []int{8}
}

func (x *GetSingleTypeRequest) GetContentTypeSlug() string {
	if x != nil {
		return x.ContentTypeSlug
	}
	return ""
}

func (x *GetSingleTypeRequest) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

type SaveSingleTypeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContentTypeSlug string                 `protobuf:"bytes,1,opt,name=content_type_slug,json=contentTypeSlug,proto3" json:"content_type_slug,omitempty"`
	Data            []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Locale          string                 `protobuf:"bytes,3,opt,name=locale,proto3" json:"locale,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SaveSingleTypeRequest) Reset() {
	*x = SaveSingleTypeRequest{}
	mi := &file_proto_cms_v1_document_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveSingleTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveSingleTypeRequest) ProtoMessage() {}

func (x *SaveSingleTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cms_v1_document_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveSingleTypeRequest.ProtoReflect.Descriptor instead.
func (*SaveSingleTypeRequest) Descriptor() ([]byte, []int) {
	return file_proto_cms_v1_document_proto_rawDescGZIP(), []int{9}
}

func (x *SaveSingleTypeRequest) GetContentTypeSlug() string {
	if x != nil {
		return x.ContentTypeSlug
	}
	return ""
}

func (x *SaveSingleTypeRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SaveSingleTypeRequest) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

var File_proto_cms_v1_document_proto protoreflect.FileDescriptor

const file_proto_cms_v1_document_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/cms/v1/document.proto\x12\x06cms.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc7\x03\n" +
	"\bDocument\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12&\n" +
	"\x0fcontent_type_id\x18\x03 \x01(\tR\rcontentTypeId\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x16\n" +
	"\x06locale\x18\x05 \x01(\tR\x06locale\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12=\n" +
	"\fpublished_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\t \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_by\x18\n" +
	" \x01(\tR\tupdatedBy\x12!\n" +
	"\fpublished_by\x18\v \x01(\tR\vpublishedBy\x12\x16\n" +
	"\x06status\x18\f \x01(\tR\x06status\"y\n" +
	"\x12GetDocumentRequest\x12*\n" +
	"\x11content_type_slug\x18\x01 \x01(\tR\x0fcontentTypeSlug\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12\x16\n" +
	"\x06locale\x18\x03 \x01(\tR\x06locale\"\x84\x01\n" +
	"\x14ListDocumentsRequest\x12*\n" +
	"\x11content_type_slug\x18\x01 \x01(\tR\x0fcontentTypeSlug\x12\x14\n" +
	"\x05start\x18\x02 \x01(\x05R\x05start\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\x12\x16\n" +
	"\x06locale\x18\x04 \x01(\tR\x06locale\"\x7f\n" +
	"\x15ListDocumentsResponse\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.cms.v1.DocumentR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x14\n" +
	"\x05start\x18\x03 \x01(\x05R\x05start\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x05R\x04size\"\x8e\x01\n" +
	"\x13SaveDocumentRequest\x12*\n" +
	"\x11content_type_slug\x18\x01 \x01(\tR\x0fcontentTypeSlug\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x16\n" +
	"\x06locale\x18\x04 \x01(\tR\x06locale\"}\n" +
	"\x16PublishDocumentRequest\x12*\n" +
	"\x11content_type_slug\x18\x01 \x01(\tR\x0fcontentTypeSlug\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12\x16\n" +
	"\x06locale\x18\x03 \x01(\tR\x06locale\"d\n" +
	"\x15DeleteDocumentRequest\x12*\n" +
	"\x11content_type_slug\x18\x01 \x01(\tR\x0fcontentTypeSlug\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\"2\n" +
	"\x16DeleteDocumentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"Z\n" +
	"\x14GetSingleTypeRequest\x12*\n" +
	"\x11content_type_slug\x18\x01 \x01(\tR\x0fcontentTypeSlug\x12\x16\n" +
	"\x06locale\x18\x02 \x01(\tR\x06locale\"o\n" +
	"\x15SaveSingleTypeRequest\x12*\n" +
	"\x11content_type_slug\x18\x01 \x01(\tR\x0fcontentTypeSlug\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x16\n" +
	"\x06locale\x18\x03 \x01(\tR\x06locale2\xc8\x05\n" +
	"\x0fDocumentService\x12;\n" +
	"\vGetDocument\x12\x1a.cms.v1.GetDocumentRequest\x1a\x10.cms.v1.Document\x12L\n" +
	"\rListDocuments\x12\x1c.cms.v1.ListDocumentsRequest\x1a\x1d.cms.v1.ListDocumentsResponse\x12=\n" +
	"\fSaveDocument\x12\x1b.cms.v1.SaveDocumentRequest\x1a\x10.cms.v1.Document\x12C\n" +
	"\x0fPublishDocument\x12\x1e.cms.v1.PublishDocumentRequest\x1a\x10.cms.v1.Document\x12E\n" +
	"\x11UnpublishDocument\x12\x1e.cms.v1.PublishDocumentRequest\x1a\x10.cms.v1.Document\x12O\n" +
	"\x0eDeleteDocument\x12\x1d.cms.v1.DeleteDocumentRequest\x1a\x1e.cms.v1.DeleteDocumentResponse\x12?\n" +
	"\rGetSingleType\x12\x1c.cms.v1.GetSingleTypeRequest\x1a\x10.cms.v1.Document\x12A\n" +
	"\x0eSaveSingleType\x12\x1d.cms.v1.SaveSingleTypeRequest\x1a\x10.cms.v1.Document\x12C\n" +
	"\x11PublishSingleType\x12\x1c.cms.v1.GetSingleTypeRequest\x1a\x10.cms.v1.Document\x12E\n" +
	"\x13UnpublishSingleType\x12\x1c.cms.v1.GetSingleTypeRequest\x1a\x10.cms.v1.DocumentB3Z1project-abyssoftime-cms-v2/api/proto/cms/v1;cmsv1b\x06proto3"

var (
	file_proto_cms_v1_document_proto_rawDescOnce sync.Once
	file_proto_cms_v1_document_proto_rawDescData []byte
)

func file_proto_cms_v1_document_proto_rawDescGZIP() []byte {
	file_proto_cms_v1_document_proto_rawDescOnce.Do(func() {
		file_proto_cms_v1_document_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cms_v1_document_proto_rawDesc), len(file_proto_cms_v1_document_proto_rawDesc)))
	})
	return file_proto_cms_v1_document_proto_rawDescData
}

var file_proto_cms_v1_document_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_cms_v1_document_proto_goTypes = []any{
	(*Document)(nil),               // 0: cms.v1.Document
	(*GetDocumentRequest)(nil),     // 1: cms.v1.GetDocumentRequest
	(*ListDocumentsRequest)(nil),   // 2: cms.v1.ListDocumentsRequest
	(*ListDocumentsResponse)(nil),  // 3: cms.v1.ListDocumentsResponse
	(*SaveDocumentRequest)(nil),    // 4: cms.v1.SaveDocumentRequest
	(*PublishDocumentRequest)(nil), // 5: cms.v1.PublishDocumentRequest
	(*DeleteDocumentRequest)(nil),  // 6: cms.v1.DeleteDocumentRequest
	(*DeleteDocumentResponse)(nil), // 7: cms.v1.DeleteDocumentResponse
	(*GetSingleTypeRequest)(nil),   // 8: cms.v1.GetSingleTypeRequest
	(*SaveSingleTypeRequest)(nil),  // 9: cms.v1.SaveSingleTypeRequest
	(*timestamppb.Timestamp)(nil),  // 10: google.protobuf.Timestamp
}
var file_proto_cms_v1_document_proto_depIdxs = []int32{
	10, // 0: cms.v1.Document.created_at:type_name -> google.protobuf.Timestamp
	10, // 1: cms.v1.Document.updated_at:type_name -> google.protobuf.Timestamp
	10, // 2: cms.v1.Document.published_at:type_name -> google.protobuf.Timestamp
	0,  // 3: cms.v1.ListDocumentsResponse.items:type_name -> cms.v1.Document
	1,  // 4: cms.v1.DocumentService.GetDocument:input_type -> cms.v1.GetDocumentRequest
	2,  // 5: cms.v1.DocumentService.ListDocuments:input_type -> cms.v1.ListDocumentsRequest
	4,  // 6: cms.v1.DocumentService.SaveDocument:input_type -> cms.v1.SaveDocumentRequest
	5,  // 7: cms.v1.DocumentService.PublishDocument:input_type -> cms.v1.PublishDocumentRequest
	5,  // 8: cms.v1.DocumentService.UnpublishDocument:input_type -> cms.v1.PublishDocumentRequest
	6,  // 9: cms.v1.DocumentService.DeleteDocument:input_type -> cms.v1.DeleteDocumentRequest
	8,  // 10: cms.v1.DocumentService.GetSingleType:input_type -> cms.v1.GetSingleTypeRequest
	9,  // 11: cms.v1.DocumentService.SaveSingleType:input_type -> cms.v1.SaveSingleTypeRequest
	8,  // 12: cms.v1.DocumentService.PublishSingleType:input_type -> cms.v1.GetSingleTypeRequest
	8,  // 13: cms.v1.DocumentService.UnpublishSingleType:input_type -> cms.v1.GetSingleTypeRequest
	0,  // 14: cms.v1.DocumentService.GetDocument:output_type -> cms.v1.Document
	3,  // 15: cms.v1.DocumentService.ListDocuments:output_type -> cms.v1.ListDocumentsResponse
	0,  // 16: cms.v1.DocumentService.SaveDocument:output_type -> cms.v1.Document
	0,  // 17: cms.v1.DocumentService.PublishDocument:output_type -> cms.v1.Document
	0,  // 18: cms.v1.DocumentService.UnpublishDocument:output_type -> cms.v1.Document
	7,  // 19: cms.v1.DocumentService.DeleteDocument:output_type -> cms.v1.DeleteDocumentResponse
	0,  // 20: cms.v1.DocumentService.GetSingleType:output_type -> cms.v1.Document
	0,  // 21: cms.v1.DocumentService.SaveSingleType:output_type -> cms.v1.Document
	0,  // 22: cms.v1.DocumentService.PublishSingleType:output_type -> cms.v1.Document
	0,  // 23: cms.v1.DocumentService.UnpublishSingleType:output_type -> cms.v1.Document
	14, // [14:24] is the sub-list for method output_type
	4,  // [4:14] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_cms_v1_document_proto_init() }
func file_proto_cms_v1_document_proto_init() {
	if File_proto_cms_v1_document_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cms_v1_document_proto_rawDesc), len(file_proto_cms_v1_document_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cms_v1_document_proto_goTypes,
		DependencyIndexes: file_proto_cms_v1_document_proto_depIdxs,
		MessageInfos:      file_proto_cms_v1_document_proto_msgTypes,
	}.Build()
	File_proto_cms_v1_document_proto = out.File
	file_proto_cms_v1_document_proto_goTypes = nil
	file_proto_cms_v1_document_proto_depIdxs = nil
}
