// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/cms/v1/media.proto

package cmsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MediaAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	ThumbnailUrl  string                 `protobuf:"bytes,4,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	PublicId      string                 `protobuf:"bytes,5,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`
	FileName      string                 `protobuf:"bytes,6,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileExt       string                 `protobuf:"bytes,7,opt,name=file_ext,json=fileExt,proto3" json:"file_ext,omitempty"`
	Hash          string                 `protobuf:"bytes,8,opt,name=hash,proto3" json:"hash,omitempty"`
	ContentTypeId string                 `protobuf:"bytes,9,opt,name=content_type_id,json=contentTypeId,proto3" json:"content_type_id,omitempty"`
	DocumentRef   string                 `protobuf:"bytes,10,opt,name=document_ref,json=documentRef,proto3" json:"document_ref,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaAsset) Reset() {
	*x = MediaAsset{}
	mi := &file_proto_cms_v1_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaAsset) ProtoMessage() {}

func (x *MediaAsset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cms_v1_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaAsset.ProtoReflect.Descriptor instead.
func (*MediaAsset) Descriptor() ([]byte, []int) {
	return file_proto_cms_v1_media_proto_rawDescGZIP(), []int{0}
}

func (x *MediaAsset) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MediaAsset) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *MediaAsset) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MediaAsset) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *MediaAsset) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *MediaAsset) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *MediaAsset) GetFileExt() string {
	if x != nil {
		return x.FileExt
	}
	return ""
}

func (x *MediaAsset) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *MediaAsset) GetContentTypeId() string {
	if x != nil {
		return x.ContentTypeId
	}
	return ""
}

func (x *MediaAsset) GetDocumentRef() string {
	if x != nil {
		return x.DocumentRef
	}
	return ""
}

func (x *MediaAsset) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMediaRequest) Reset() {
	*x = ListMediaRequest{}
	mi := &file_proto_cms_v1_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMediaRequest) ProtoMessage() {}

func (x *ListMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cms_v1_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMediaRequest.ProtoReflect.Descriptor instead.
func (*ListMediaRequest) Descriptor() ([]byte, []int) {
	return file_proto_cms_v1_media_proto_rawDescGZIP(), []int{1}
}

func (x *ListMediaRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMediaRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assets        []*MediaAsset          `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMediaResponse) Reset() {
	*x = ListMediaResponse{}
	mi := &file_proto_cms_v1_media_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMediaResponse) ProtoMessage() {}

func (x *ListMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cms_v1_media_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMediaResponse.ProtoReflect.Descriptor instead.
func (*ListMediaResponse) Descriptor() ([]byte, []int) {
	return file_proto_cms_v1_media_proto_rawDescGZIP(), []int{2}
}

func (x *ListMediaResponse) GetAssets() []*MediaAsset {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *ListMediaResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DeleteMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMediaRequest) Reset() {
	*x = DeleteMediaRequest{}
	mi := &file_proto_cms_v1_media_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMediaRequest) ProtoMessage() {}

func (x *DeleteMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cms_v1_media_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMediaRequest.ProtoReflect.Descriptor instead.
func (*DeleteMediaRequest) Descriptor() ([]byte, []int) {
	return file_proto_cms_v1_media_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteMediaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMediaResponse) Reset() {
	*x = DeleteMediaResponse{}
	mi := &file_proto_cms_v1_media_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMediaResponse) ProtoMessage() {}

func (x *DeleteMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cms_v1_media_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMediaResponse.ProtoReflect.Descriptor instead.
func (*DeleteMediaResponse) Descriptor() ([]byte, []int) {
	return file_proto_cms_v1_media_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteMediaResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_cms_v1_media_proto protoreflect.FileDescriptor

const file_proto_cms_v1_media_proto_rawDesc = "" +
	"\n" +
	"\x18proto/cms/v1/media.proto\x12\x06cms.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe3\x02\n" +
	"\n" +
	"MediaAsset\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12#\n" +
	"\rthumbnail_url\x18\x04 \x01(\tR\fthumbnailUrl\x12\x1b\n" +
	"\tpublic_id\x18\x05 \x01(\tR\bpublicId\x12\x1b\n" +
	"\tfile_name\x18\x06 \x01(\tR\bfileName\x12\x19\n" +
	"\bfile_ext\x18\a \x01(\tR\afileExt\x12\x12\n" +
	"\x04hash\x18\b \x01(\tR\x04hash\x12&\n" +
	"\x0fcontent_type_id\x18\t \x01(\tR\rcontentTypeId\x12!\n" +
	"\fdocument_ref\x18\n" +
	" \x01(\tR\vdocumentRef\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"<\n" +
	"\x10ListMediaRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"U\n" +
	"\x11ListMediaResponse\x12*\n" +
	"\x06assets\x18\x01 \x03(\v2\x12.cms.v1.MediaAssetR\x06assets\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"$\n" +
	"\x12DeleteMediaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"/\n" +
	"\x13DeleteMediaResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x98\x01\n" +
	"\fMediaService\x12@\n" +
	"\tListMedia\x12\x18.cms.v1.ListMediaRequest\x1a\x19.cms.v1.ListMediaResponse\x12F\n" +
	"\vDeleteMedia\x12\x1a.cms.v1.DeleteMediaRequest\x1a\x1b.cms.v1.DeleteMediaResponseB3Z1project-abyssoftime-cms-v2/api/proto/cms/v1;cmsv1b\x06proto3"

var (
	file_proto_cms_v1_media_proto_rawDescOnce sync.Once
	file_proto_cms_v1_media_proto_rawDescData []byte
)

func file_proto_cms_v1_media_proto_rawDescGZIP() []byte {
	file_proto_cms_v1_media_proto_rawDescOnce.Do(func() {
		file_proto_cms_v1_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cms_v1_media_proto_rawDesc), len(file_proto_cms_v1_media_proto_rawDesc)))
	})
	return file_proto_cms_v1_media_proto_rawDescData
}

var file_proto_cms_v1_media_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_cms_v1_media_proto_goTypes = []any{
	(*MediaAsset)(nil),            // 0: cms.v1.MediaAsset
	(*ListMediaRequest)(nil),      // 1: cms.v1.ListMediaRequest
	(*ListMediaResponse)(nil),     // 2: cms.v1.ListMediaResponse
	(*DeleteMediaRequest)(nil),    // 3: cms.v1.DeleteMediaRequest
	(*DeleteMediaResponse)(nil),   // 4: cms.v1.DeleteMediaResponse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_proto_cms_v1_media_proto_depIdxs = []int32{
	5, // 0: cms.v1.MediaAsset.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: cms.v1.ListMediaResponse.assets:type_name -> cms.v1.MediaAsset
	1, // 2: cms.v1.MediaService.ListMedia:input_type -> cms.v1.ListMediaRequest
	3, // 3: cms.v1.MediaService.DeleteMedia:input_type -> cms.v1.DeleteMediaRequest
	2, // 4: cms.v1.MediaService.ListMedia:output_type -> cms.v1.ListMediaResponse
	4, // 5: cms.v1.MediaService.DeleteMedia:output_type -> cms.v1.DeleteMediaResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_cms_v1_media_proto_init() }
func file_proto_cms_v1_media_proto_init() {
	if File_proto_cms_v1_media_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cms_v1_media_proto_rawDesc), len(file_proto_cms_v1_media_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cms_v1_media_proto_goTypes,
		DependencyIndexes: file_proto_cms_v1_media_proto_depIdxs,
		MessageInfos:      file_proto_cms_v1_media_proto_msgTypes,
	}.Build()
	File_proto_cms_v1_media_proto = out.File
	file_proto_cms_v1_media_proto_goTypes = nil
	file_proto_cms_v1_media_proto_depIdxs = nil
}
