// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type ContentType struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	Kind      string    `json:"kind"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type Document struct {
	DocumentID    string         `json:"documentId"`
	Version       string         `json:"version"`
	ContentTypeID string         `json:"contentTypeId"`
	Data          map[string]any `json:"data"`
	Locale        string         `json:"locale"`
	CreatedAt     time.Time      `json:"createdAt"`
	UpdatedAt     time.Time      `json:"updatedAt"`
	PublishedAt   *time.Time     `json:"publishedAt,omitempty"`
	CreatedBy     string         `json:"createdBy"`
	UpdatedBy     string         `json:"updatedBy"`
	PublishedBy   *string        `json:"publishedBy,omitempty"`
}

type Mutation struct {
}

type Query struct {
}
